# Alacritty Config File
# vsec
# 04.09.24

[window]
opacity = 0.6

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal.family = "0xProto Nerd Font"
bold.family = "0xProto Nerd Font"  
italic.family = "0xProto Nerd Font"
bold_italic.family = "0xProto Nerd Font"

size = 12.0
